Hw 1
Sensorzxc/ml_hw pull request #1
Opened 2024-02-04 14:53 UTC by Sensorzxc

2024-02-10 07:59 UTC, svkov requested changes
Переделай первую, остальное ок

2024-02-10 07:59 UTC, svkov commented on notebooks/01-homework.ipynb
> +    "from statistics import mean, median, multimode\n",
Так делать нельзя, в дз есть ограничение на использование библиотек.

2024-02-10 07:59 UTC, svkov commented on notebooks/01-homework.ipynb
> +    "with open('/home/sensor/ml_hw/data/dota_hero_stats.csv', 'r') as file:\n",
Лучше использовать относительные пути. Если бы я скачал репозиторий себе на компьютер, у меня бы не заработало.

2024-02-10 07:59 UTC, svkov commented on notebooks/01-homework.ipynb
> +    "        if values[4] == 'Zeus':\n",
Чем тебе Зевс не угодил?)

2024-02-13 19:56 UTC, Sensorzxc commented on notebooks/01-homework.ipynb
> +    "        if values[4] == 'Zeus':\n",
у него там в данных чуть другой формат (у всех роли записаны как массив [], а у него просто название

2024-02-20 07:17 UTC, svkov commented
Дедлайн по исправлениям первой домашки прошел

2024-03-22 19:48 UTC, merged